var a = 10;
document.write("<h3>Result<h3>");
document.write("<h4>The value of a : "+ a + "<br>" );
++a;
document.write("The value of ++a is : " + a +"<br>");
document.write("Now the value of a is : "+ a +"<br>");
a++;
document.write("The value of a++ is :"+a+"<br>");
document.write("Now the value of a is : "+a+"<br>");
--a;
document.write("The value of --a is : "+a+"<br>");
document.write("Now the value of a is : "+a+"<br>");
a--;
document.write("The value of a-- is : "+a+"<br>");
document.write("Now the value of a is : "+a+"<br>");
